- hosts: develop
  become: yes

  tasks:
    - name: install guake
      apt:
        name: guake
        state: present
        update_cache: yes

  tasks:
    - name: guake autostart
      copy:
        src: /usr/share/applications/guake.desktop 
        dest: /etc/xdg/autostart/
        force: no

